networks:
  go:
    driver: bridge

volumes:
  goroot:
  gocache:
  pgdata:

services:
  auth_service:
    container_name: auth_service
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - auth_db

  auth_db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - 5432:5432